# Generated by Django 3.2.7 on 2021-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveaudio',
            name='media',
            field=models.FilePathField(),
        ),
    ]
