# Generated by Django 3.2.7 on 2021-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_archiveaudio_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveaudio',
            name='media',
            field=models.CharField(max_length=100),
        ),
    ]
