# Generated by Django 3.2.7 on 2021-11-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_storearchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveaudio',
            name='category',
        ),
    ]
