# Generated by Django 3.2.7 on 2021-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_archiveaudio_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivemedia',
            name='category',
        ),
        migrations.RemoveField(
            model_name='archivevideo',
            name='category',
        ),
        migrations.AlterField(
            model_name='archivemedia',
            name='media',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='archivevideo',
            name='media',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
