# Generated by Django 3.2.7 on 2021-11-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211118_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchiveMedia',
            new_name='ArchivePhoto',
        ),
    ]
